-- Seed the controlled vocabulary (section 60 of the spec).
-- These are starting values; more can be added later from the app or by the AI
-- pipeline when a genuinely new concept appears.

INSERT INTO tags (canonical_name, category) VALUES
  ('Alan', 'CHARACTER'),
  ('Mia', 'CHARACTER'),

  ('Streaming', 'ACTIVITY'),
  ('Using computer', 'ACTIVITY'),
  ('Playing music', 'ACTIVITY'),
  ('Playing guitar', 'ACTIVITY'),
  ('Using Ableton', 'ACTIVITY'),
  ('Listening to music', 'ACTIVITY'),
  ('Drinking', 'ACTIVITY'),
  ('Sleeping', 'ACTIVITY'),
  ('Dancing', 'ACTIVITY'),
  ('Walking', 'ACTIVITY'),
  ('Talking', 'ACTIVITY'),
  ('Working', 'ACTIVITY'),
  ('Performing', 'ACTIVITY'),
  ('Partying', 'ACTIVITY'),
  ('Driving', 'ACTIVITY'),

  ('Bedroom', 'LOCATION'),
  ('Apartment', 'LOCATION'),
  ('Studio', 'LOCATION'),
  ('Club', 'LOCATION'),
  ('Bar', 'LOCATION'),
  ('Street', 'LOCATION'),
  ('Concert', 'LOCATION'),
  ('Stage', 'LOCATION'),
  ('Car', 'LOCATION'),
  ('Kitchen', 'LOCATION'),
  ('Bathroom', 'LOCATION'),
  ('Outdoors', 'LOCATION'),

  ('Happy', 'MOOD'),
  ('Sad', 'MOOD'),
  ('Angry', 'MOOD'),
  ('Frustrated', 'MOOD'),
  ('Tired', 'MOOD'),
  ('Drunk', 'MOOD'),
  ('Calm', 'MOOD'),
  ('Excited', 'MOOD'),
  ('Neutral', 'MOOD'),
  ('Lonely', 'MOOD'),
  ('Stressed', 'MOOD'),

  ('Day', 'TIME'),
  ('Night', 'TIME'),
  ('Sunset', 'TIME'),
  ('Dark interior', 'TIME'),
  ('Artificial lighting', 'TIME'),

  ('Close-up', 'SHOT_TYPE'),
  ('Medium close-up', 'SHOT_TYPE'),
  ('Medium shot', 'SHOT_TYPE'),
  ('Medium wide', 'SHOT_TYPE'),
  ('Wide shot', 'SHOT_TYPE'),
  ('Full body', 'SHOT_TYPE'),

  ('Front', 'CAMERA_ANGLE'),
  ('Profile', 'CAMERA_ANGLE'),
  ('Three-quarter', 'CAMERA_ANGLE'),
  ('Back', 'CAMERA_ANGLE'),
  ('Low angle', 'CAMERA_ANGLE'),
  ('High angle', 'CAMERA_ANGLE'),
  ('Over-the-shoulder', 'CAMERA_ANGLE'),

  ('Sitting', 'POSE'),
  ('Standing', 'POSE'),
  ('Lying down', 'POSE'),
  ('Walking', 'POSE'),
  ('Dancing', 'POSE'),
  ('Leaning', 'POSE'),

  ('Computer', 'OBJECT'),
  ('Laptop', 'OBJECT'),
  ('Headphones', 'OBJECT'),
  ('Guitar', 'OBJECT'),
  ('Phone', 'OBJECT'),
  ('Bottle', 'OBJECT'),
  ('Glass', 'OBJECT'),
  ('Bed', 'OBJECT'),
  ('Desk', 'OBJECT'),
  ('Keyboard', 'OBJECT'),
  ('Microphone', 'OBJECT'),
  ('Speaker', 'OBJECT');
